dist: trusty
sudo: required

node_js:
  - 6

addons:
  sonarcloud:
    organization: default
    token:
      secure: ""

install:
  - npm install

before_script:
  - npm install -g gulp

script:
  npm test
  gulp
