dist: trusty
sudo: required

node_js:
  - 8.11.2

addons:
  sonarcloud:
    organization: default
    token:
      secure: ""

install:
  - npm install

before_script:
  - npm install -g gulp

script:
  npm test
  gulp

after_success: npm run coverage

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release